### ISSUE TITLE
Player_group table

### ISSUE THREAD

**Issue by CavemanTi** [Qbox-project/qbx_core#413] opened 2024-03-12 17:20 UTC
### Summary

Loading the SQL into the data base I get an SQL Error (1005) Foreign Key constraint is incorrectly formed

### Reproduction

![image](https://github.com/Qbox-project/qbx_core/assets/158537382/e2e8a907-e501-45ca-ba7c-81c0fe3b4c11)
![image](https://github.com/Qbox-project/qbx_core/assets/158537382/aabbba21-336e-4cbe-a8cb-f13f62b5fbb7)

### Expected behavior

SQL to load into the database

### Actual behavior

Player group is not loading into the database, SQL error

### Current Version

1.8

### Custom Resources

qbox

**Comment by Manason** [comment] 2024-03-12 17:28
I assume this a conversion case and not a fresh recipe install.

See step 5 on https://docs.qbox.re/converting

You'll need to modify the collation of player.citizenid

**Comment by CavemanTi** [comment] 2024-03-12 21:31
We are using Qbox not qb-core

**Comment by Manason** [comment] 2024-03-12 21:39
> We are using Qbox not qb-core

Are you converting a server or downloading the recipe?

**Comment by CavemanTi** [comment] 2024-03-15 00:04
We built the server off qbox from the start. It was never converted from qb

**Comment by CavemanTi** [comment] 2024-03-15 00:04
sorry for the long delay

**Comment by Manason** [comment] 2024-03-15 02:12
The issue is likely your collation of player.citizenid. Please use the discord for support. Closing as this is not a bug.

**Closed by Manason** 2024-03-15 02:12 UTC
Labels: bug, need repro
