### ISSUE TITLE
Motorcycle spawning crashes all players & request server restart.

### ISSUE THREAD

**Issue by AJCorwin** [Qbox-project/qbx_core#484] opened 2024-06-10 03:50 UTC
### Summary

Anytime I try to spawn motorcycles within the city all players crash. When attempting to rejoin the city the player will crash until the city is restarted.

### Reproduction

1. Add motorcycle that does not use a base motorcycle as the back end to a vehicles folder.
2. Spawn the motorcycle using tx admin or any other admin program.
3. Crash
4. Attempt to rejoin server and crash.

### Expected behavior

The vehicle spawns and does not crash the players / server.

### Actual behavior

The vehicle does not spawn and all players crash with the same error.

### Additional context

Note this only happens on servers that are not locally hosted. 

The distance between players does not matter, you can be on totally different sides of the map. I can provide some vehicles to the team if it would help.

[CitizenFX_log_2024-06-09T231055.log](https://github.com/user-attachments/files/15756199/CitizenFX_log_2024-06-09T231055.log)

### Current Version

1.14.1

### Custom Resources

919 admin menu

**Comment by AJCorwin** [comment] 2024-06-10 04:00
Qbox version info: I installed a brand new version of a non lean Qbox server today following the instructions in the documentation.
TxAdmin version is 7.1.0
919 does not seem to change any behavior from what I can tell.
I verified the hash on my local machine before transfer and after transferring the vehicle and it is the same hash ID. I used the command in powershell below.
Get-FileHash -Path ".\monowheel.yft" -Algorithm SHA256

Unknown Fivem build / artifact version but I still have the initial download which can be provided upon request.

There is not an error within the server console which is why this has been so hard to hunt down.

**Comment by mafewtm** [comment] 2024-06-10 04:03
So is this with all motorcycles or just a custom one?

**Comment by AJCorwin** [comment] 2024-06-10 04:06
It seems to be with only custom motorcycles. I can spawn any base GTA/GTA:O motorcycle without issue. I also have a reskinned base GTA motorcycle that does not cause any issues.

I did have one car cause the issue but I simply removed it.

**Comment by mafewtm** [comment] 2024-06-10 04:06
It sounds like an issue with the models, not an issue with our core

**Comment by AJCorwin** [comment] 2024-06-10 04:09
I can provide a motorcycle for you to test against. 

I have tried 12 different motorcycles so far, I just installed artifact version 8445 and the issue persist.

**Comment by mafewtm** [comment] 2024-06-10 04:14
It seems like its something you're doing then. I've tested import motorcycles and it worked fine and as you've said, your friend tested it as well and it works fine. I'm just curious what exactly you're doing wrong

**Comment by AJCorwin** [comment] 2024-06-10 04:18
I created a [Vehicles] folder, create a sub folder called motorcycles. Inside of the motorcycles folder I have a data and stream folder.

I create a folder within each labeled the bikes name then split out the files according to the folder they belong in.

I have also tried making separate [VehicleMeta] and [VehicleStream] folders with motorcycles_meta and motorcycles_stream.

I face the same issue either way.

**Comment by Manason** [comment] 2024-06-10 06:57
How are you spawning the motorcycles? Are you using the qbx lib? If so, does it work if you spawn them without using the qbx lib?

**Comment by CarlBishop** [comment] 2024-06-10 09:40
I had same issue years ago.
The issue was caused by wrongly resized textures. Check textures, do not compress or resize it.
XNRESIZE sometimes (more often then sometines) has strange behaviour with some textures.

**Comment by Manason** [comment] 2024-06-10 09:47
Going to close this out as it doesn't seem related to an issue with Qbox. Feel free to continue to seek support in the discord.

**Closed by Manason** 2024-06-10 09:47 UTC
Labels: bug, need repro
